# Welcome to Serverless!
# This is the betterPT serverless typescript boilerplate

service: service-name

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
    environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
 region: us-east-1
 stage: ${opt:stage}
 
package:
  exclude:
    - tsconfig.json
    - tslint.json

functions:
  hello:
    handler: service/hello.handler